version: '2'
services:
  db:
    image: mongo
    container_name: summer2016-db
    volumes:
      - /data/summer2016:/data/db
  web:
    build: .
    container_name: summer2016-web
    depends_on:
      - db

    

